### ISSUE TITLE
The value '\Intelipost\Autocomplete\Block\Url' is not accepted by the pattern

### ISSUE THREAD

**Issue by jrmaia** [intelipost/magento2-autocomplete#3]
Instalei o módulo de Autocomplete, e quando entro no checkout do site, o magento quebra com a seguinte mensagem na tela:

`1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'block', attribute 'class': [facet 'pattern'] The value '\Intelipost\Autocomplete\Block\Url' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 1740

Element 'block', attribute 'class': '\Intelipost\Autocomplete\Block\Url' is not a valid value of the atomic type 'blockClassType'.
Line: 1740

Element 'block', attribute 'class': [facet 'pattern'] The value '\Intelipost\Autocomplete\Block\Order' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 1741

Element 'block', attribute 'class': '\Intelipost\Autocomplete\Block\Order' is not a valid value of the atomic type 'blockClassType'.
Line: 1741

Element 'item': Duplicate key-sequence ['children'] in key identity-constraint 'itemName'.
Line: 1862

Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'block', attribute 'class': [facet 'pattern'] The value '\Intelipost\Autocomplete\Block\Url' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 1740

Element 'block', attribute 'class': '\Intelipost\Autocomplete\Block\Url' is not a valid value of the atomic type 'blockClassType'.
Line: 1740

Element 'block', attribute 'class': [facet 'pattern'] The value '\Intelipost\Autocomplete\Block\Order' is not accepted by the pattern '[A-Z][_a-zA-Z\d]*(\\[A-Z][_a-zA-Z\d]*)*'.
Line: 1741

Element 'block', attribute 'class': '\Intelipost\Autocomplete\Block\Order' is not a valid value of the atomic type 'blockClassType'.
Line: 1741

Element 'item': Duplicate key-sequence ['children'] in key identity-constraint 'itemName'.
Line: 1862

#0 /home/netembal/public_html/novosite/vendor/magento/framework/Config/Dom.php(115): Magento\Framework\Config\Dom->_initDom('<layout xmlns:x...')
#1 /home/netembal/public_html/novosite/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Magento\Framework\Config\Dom->__construct('<layout xmlns:x...', Object(Magento\Framework\App\Arguments\ValidationState), Array, NULL, '/home/netembal/...', '%message%\nLine:...')
#2 /home/netembal/public_html/novosite/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#3 /home/netembal/public_html/novosite/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...', Array)
#4 /home/netembal/public_html/novosite/vendor/magento/framework/Config/DomFactory.php(42): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
#5 /home/netembal/public_html/novosite/vendor/magento/framework/View/Model/Layout/Update/Validator.php(141): Magento\Framework\Config\DomFactory->createDom(Array)
#6 /home/netembal/public_html/novosite/vendor/magento/framework/View/Model/Layout/Merge.php(461): Magento\Framework\View\Model\Layout\Update\Validator->isValid('<layout xmlns:x...', 'layout_merged', false)
#7 /home/netembal/public_html/novosite/vendor/magento/framework/View/Model/Layout/Merge.php(442): Magento\Framework\View\Model\Layout\Merge->_validateMergedLayout('LAYOUT_frontend...', '<body>\n   <refe...')
#8 /home/netembal/public_html/novosite/vendor/magento/framework/View/Layout/Builder.php(86): Magento\Framework\View\Model\Layout\Merge->load()
#9 /home/netembal/public_html/novosite/vendor/magento/framework/View/Layout/Builder.php(63): Magento\Framework\View\Layout\Builder->loadLayoutUpdates()
#10 /home/netembal/public_html/novosite/vendor/magento/framework/View/Page/Config.php(197): Magento\Framework\View\Layout\Builder->build()
#11 /home/netembal/public_html/novosite/vendor/magento/framework/View/Page/Config.php(217): Magento\Framework\View\Page\Config->build()
#12 /home/netembal/public_html/novosite/vendor/magento/module-checkout/Controller/Index/Index.php(39): Magento\Framework\View\Page\Config->getTitle()
#13 /home/netembal/public_html/novosite/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Controller\Index\Index->execute()
#14 /home/netembal/public_html/novosite/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Controller\Index\Index\Interceptor->___callParent('execute', Array)
#15 /home/netembal/public_html/novosite/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Controller\Index\Index\Interceptor->Magento\Framework\Interception\{closure}()
#16 /home/netembal/public_html/novosite/generated/code/Magento/Checkout/Controller/Index/Index/Interceptor.php(26): Magento\Checkout\Controller\Index\Index\Interceptor->___callPlugins('execute', Array, Array)
#17 /home/netembal/public_html/novosite/vendor/magento/framework/App/Action/Action.php(107): Magento\Checkout\Controller\Index\Index\Interceptor->execute()
#18 /home/netembal/public_html/novosite/vendor/magento/module-checkout/Controller/Onepage.php(161): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#19 /home/netembal/public_html/novosite/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Controller\Onepage->dispatch(Object(Magento\Framework\App\Request\Http))
#20 /home/netembal/public_html/novosite/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Controller\Index\Index\Interceptor->___callParent('dispatch', Array)
#21 /home/netembal/public_html/novosite/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Controller\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#22 /home/netembal/public_html/novosite/generated/code/Magento/Checkout/Controller/Index/Index/Interceptor.php(39): Magento\Checkout\Controller\Index\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#23 /home/netembal/public_html/novosite/vendor/magento/framework/App/FrontController.php(55): Magento\Checkout\Controller\Index\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#24 /home/netembal/public_html/novosite/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#25 /home/netembal/public_html/novosite/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#26 /home/netembal/public_html/novosite/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#27 /home/netembal/public_html/novosite/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#28 /home/netembal/public_html/novosite/app/code/Litespeed/Litemage/Model/App/FrontController/LitemagePlugin.php(71): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#29 /home/netembal/public_html/novosite/vendor/magento/framework/Interception/Interceptor.php(135): Litespeed\Litemage\Model\App\FrontController\LitemagePlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#30 /home/netembal/public_html/novosite/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#31 /home/netembal/public_html/novosite/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#32 /home/netembal/public_html/novosite/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#33 /home/netembal/public_html/novosite/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#34 /home/netembal/public_html/novosite/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#35 /home/netembal/public_html/novosite/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#36 /home/netembal/public_html/novosite/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))`

Alguém sabe o que pode ser?

**Comment by Jackcar** [comment]
Consegui arrumar este erro, voce precisa editar os seguintes arquivos:
- magento\vendor\intelipost\magento2-autocomplete\view\frontend\layout\checkout_index_index.xml
- magento\vendor\intelipost\magento2-autocomplete\view\frontend\layout\customer_account_create.xml
- magento\vendor\intelipost\magento2-autocomplete\view\frontend\layout\customer_address_form.xml

Em cada arquivo, tera uma referencia de cada bloco, mude de:
<block **class="\Intelipost\Autocomplete\Block\Url"**   template="url.phtml"   name="intelipost_autocomplete_url"   after="order_content" />

Para (Retirando a contra barra no inicio do path):
<block **class="Intelipost\Autocomplete\Block\Url"**   template="url.phtml"   name="intelipost_autocomplete_url"   after="order_content" />

**Comment by Arik-S** [comment]
@Jackcar 

Thank you very much.
